### ISSUE TITLE
Missing slash '/' in a topic name

### ISSUE THREAD

**Issue by Vourhey** [airalab/robonomics_comm#106]
If an objective.bag's topic name doesn't start with a slash '/', the name of the topic is wrong

Example:
```
/liability/eth_0xfD0B71Ade6c26AE1B59fbeDDe2edaaf965befF42/task   # should be like this
/liability/eth_0xfD0B71Ade6c26AE1B59fbeDDe2edaaf965befF42task    # but got this
```

The rosbag file used in this case
[objective1.bag.zip](https://github.com/airalab/robonomics_comm/files/3143591/objective1.bag.zip)

**Comment by strdn** [comment]
Closed in #109
