### ISSUE TITLE
Execute arbitrary liability by address

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics_comm#108]
Hi.

Currently one can execute liability catching it from `liability` node API or publishing *Liability* type message in topic `/liability/incoming` with all parameters of liability contract exists in blockchian. It's possible to fetch all message fields by given liability contract address. Can you implement this API method? For example, `/liability/resume` service can be overloaded with this functionality.

**Comment by strdn** [comment]
`/liability/reproduce` looks better in my opinion.

**Comment by akru** [comment]
IMHO we just have a service to execute any liability by address, it also could be used by liability engine or any another staff.

**Comment by strdn** [comment]
/liability/start can load and play arbitrary liability
