### ISSUE TITLE
Liability node failure: ValueError -32000 "Filter not found"

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics_comm#29]
Robonomics liability node fails with an error mentioned in the title, please find logs below. Restart helps.

Version: latest from airapkgs at 25.09.2018,
Launch file: default,
Ethereum: mainnet.

<details>
  <summary>roslaunch robonomics_liability liability.launch</summary>

![image](https://user-images.githubusercontent.com/833019/46070114-0ea4d380-c18e-11e8-8555-de160454377f.png)

</details>

[liability-infochan-channel-1.log](https://github.com/airalab/robonomics_comm/files/2418967/liability-infochan-channel-1.log)
[liability-infochan-signer-2.log](https://github.com/airalab/robonomics_comm/files/2418968/liability-infochan-signer-2.log)
[roslaunch-aira-01-23226.log](https://github.com/airalab/robonomics_comm/files/2418969/roslaunch-aira-01-23226.log)
[liability-listener-3.log](https://github.com/airalab/robonomics_comm/files/2418970/liability-listener-3.log)
[liability-executor-4.log](https://github.com/airalab/robonomics_comm/files/2418971/liability-executor-4.log)
[parity.log](https://github.com/airalab/robonomics_comm/files/2418972/parity.log)

**Comment by akru** [comment]
@strdn looks like needed to catch an exception and recreate event filter.
