### ISSUE TITLE
Signer node fails on signature request rejected

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics_comm#32]
Please consider a log folded below.

How to reproduce:
1. Launch liability package with your `parity-ethereum` client,
```bash
roslaunch robonomics_liability liability.launch web3_http_provider=http://<your_node_ip>:8545
```
2. Publish robonomics_lighthouse/Result type message to `/liability/infochain/signing/result`
```bash
rostopic pub -1  robonomics_lighthouse/Result /liability/infochain/signing/result <your_msg>
```
3. Open `parity-ui` and `reject` signature request.

Behavior desired:
IDK, let's discuss.

<details>
  <summary>roslaunch robonomics_liability liability.launch</summary>

![image](https://user-images.githubusercontent.com/833019/46250036-18576100-c444-11e8-96f2-a882406cac13.png)

</details>

**Comment by akru** [comment]
Is not actual by https://github.com/airalab/robonomics_comm/pull/35
