### ISSUE TITLE
Listener node fails with web3 BadFunctionCallOutput

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics_comm#33]
While parity synced `robonomics_liability` service fails, please consider a log below. I'll try to collect more data to specify reproduction steps.

![image](https://user-images.githubusercontent.com/833019/46274515-cc530c00-c56a-11e8-96f0-545535a9b3e3.png)

**Comment by akru** [comment]
Are your chain is fully synchronized?

**Comment by khssnv** [comment]
When I find it, parity had latest block number. I'd like to have a tool for logs capture to take it all automatically even when I have no time to leave system unavailable. Are they all in /var/lib/<service_user>/logs or you like to have any more on failure occurred?

**Comment by akru** [comment]
Currently this error should not crash service, you are free to reopen issue when more data will collected.
