### ISSUE TITLE
Executor node fails on attempt to get an account address

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics_comm#38]
I set `account_address` parameter but node attempts to get address from a client. Seems like parameter namespace error. Please consider log and launchfile screenshot below.

**How to reproduce**
1. Setup your public node with no accounts in it,
```bash
$ parity --public-node --jsonrpc-interface=0.0.0.0 --jsonrpc-port=8545 --jsonrpc-apis "eth,net,web3,personal,parity"
```
2. Set valid "account_address", "keyfile" path, "keyfile_password_file" path and "web3_http_provider" to node you set at step `1`,
3. Launch `robonomics_liability`,
4. Wait few seconds.

**Behavior desirable**
Get actual account from a `keyfile` or at least from `account_address` parameter with no error.

<details>
  <summary>Left: $ roslaunch robonomics_liability liability.launch | Right: $ nano liability.launch </summary>

![image](https://user-images.githubusercontent.com/833019/46565356-2a8b4080-c917-11e8-9699-9de0f3c2bd3b.png)
<details>

**Comment by strdn** [comment]
@khssnv, please try again. Issue is fixed now.
