### ISSUE TITLE
Stable branch for robonomics_comm

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics_comm#40]
Forcing both our development and software usage we facing with situations where we have no working system in a latest commit while users need it to use outside of AIRA/Nix. Seems like it's time to make a kind of "stabe, unstable and devel" branches. Don't you think so?

**Comment by akru** [comment]
It's already exist, https://github.com/airalab/aira/releases is stable, any other is unstable and for developers only.

**Comment by akru** [comment]
I mean `airapkgs` snapshot in https://github.com/airalab/aira repo is stable and low updating rate, but `robonomics_comm` repo is apriory unstable and release of this should be stabilized before writing to https://github.com/airalab/aira.
