### ISSUE TITLE
Finish and/or restart for interrupted liability execution

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics_comm#62]
Now I use only short exection models no longer a minutes, but I hope to develop CPS with liabilities take days or weeks to complete. The main reason to make it short now because if something goes wrong while liability exection like application software error, server restart or batteries dischage - liability execution interrupts with no way to continue or even restart it.

I see there are open questions on how to _continue_ interrupted execution with no missing older _report_ data, for example.

But maybe it's possible to implement _restart_ execution or even just allow to finish own liability which is not finished yet?

**Comment by khssnv** [comment]
Any updates for this topic?

**Comment by akru** [comment]
Available on `robonomics_liability-nightly`.

**Comment by strdn** [comment]
@akru, working on this issue in not finished yet.

**Comment by akru** [comment]
Rly? Please let me known when finish.

**Comment by strdn** [comment]
@akru, please see PR #89

**Comment by akru** [comment]
@strdn released as `nightly`

**Comment by strdn** [comment]
@khssnv, please see #89 description and feel free to ask any question about new behaviour
