### ISSUE TITLE
Executor ipfs.add returns a list but should dict

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics_comm#8]
Hi. I use liability node with default launch parameters. On result publishing I've got an exception you may find on a screenshot above. Whats wrong?

![image](https://user-images.githubusercontent.com/833019/42746787-6aa5587e-88fb-11e8-9992-ff57d3bf92f8.png)

ipfs version 0.4.15
NixOS 18.09.git.a50a99a

**Comment by khssnv** [comment]
Can't reproduce. Another try with printing ipfs.add output to log finished fine.
![image](https://user-images.githubusercontent.com/833019/42747519-86106858-88fe-11e8-9f62-6b260c551fee.png)

**Comment by akru** [comment]
You are free to reopen if you are reproduce it in the future.

**Comment by khssnv** [comment]
I just got this error again in the same environment. We should check ipfsapi add realization behavior or runtime check what it returns kinda like:
`
add_output = self.ipfs.add(result_file)
msg.result = add_output['Hash'] if type(add_output) == dict else add_output[0]['Hash']
`

**Comment by akru** [comment]
Could you provide ipfs returned values in both cases?

**Comment by khssnv** [comment]
IPFS API [unfolds](https://github.com/ipfs/py-ipfs-api/blob/master/ipfsapi/http.py#L119) original provider response from a list to dict if it contains just one item. But if an error occurs while provider proceeding request it returns a list with two item (expected dict and a message dict) even if we add one file. You can see the returned values below. I've open an [issue](https://github.com/ipfs/py-ipfs-api/issues/133) in IPFS API repository, maybe they know a better place for error messages.

No errors (returns dict as expected):
```python
>>> ipfsapi.connect('http://127.0.0.1', 5001).add('./myfile')
{'Name': 'myfile', 'Hash': 'QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH', 'Size': '6'}
```

With a error (returns a list with error message):
```python
>>> ipfsapi.connect('http://127.0.0.1', 5001).add('./myfile')
[{'Name': 'myfile', 'Hash': 'QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH', 'Size': '6'},
{'Message': 'cannot store pin state: write /var/lib/ipfs/datastore/000014.log: no space left on device', 'Code': 0, 'Type': 'error'}]
```

**Comment by khssnv** [comment]
Please consider my PR to prevent liability node crashes in a such situation: https://github.com/airalab/robonomics_comm/pull/12

**Comment by akru** [comment]
Is stored with error file available on your node? Or we need to store file again?

**Comment by khssnv** [comment]
If you mean a file I try to add, yes it becomes available by IPFS after adding it. The only trouble is to get its hash in a proper way.

**Comment by akru** [comment]
Ok, nice, thanks for your work!
