### ISSUE TITLE
Promisee and promisor fields in robonomics market ROS messages

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics_comm#90]
In offer and demand processing it would be great to know an ID of a party sent this message. Could we add this filed to market ROS messages, I mean Offer and Demand types?

**Comment by strdn** [comment]
@khssnv, please see https://github.com/strdn/robonomics_comm/blob/b9337c86b97b4f50f6f22bc80da98bd73c661647/robonomics_msgs/src/robonomics_msgs/robonomicsMessageUtils.py

**Comment by khssnv** [comment]
@strdn, seems cool, but need an example.

**Comment by strdn** [comment]
@khssnv,
you can use robonomicsMessageUtils.get_result_msg_sender_address(result) method for getting sender of Result.msg message 
and
use sender field directly for Demand and Offer messages
