### ISSUE TITLE
Objective player for services without liability contract

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics_comm#96]
When I use robonomics protocol to let user use a CPS service for free, I mean when on `Demand` recieved I do something immediately and return a `Result` type message, I currently have to implement my own objective player.

`Result` response packing support necessary as well. You may consider manually packing [here](https://github.com/khssnv/my_weather/blob/7799d07795de8983960a749054f916142904cffb/my_weather_acl/scripts/worker_node#L152).

**Enhancement proposal**
1. Implement #86 to manupulate with model and objective data,
1. Implement objective player (or more general framework) for services without liability contracts.
1. [WIP]

**Comment by strdn** [comment]
Closed in #109
